// import { DummyRestaurantData } from "@/components/common/types";

// export const dummyRestaurantList: DummyRestaurantData[] = [
//   {
//     id: 1,
//     name: "Saku",
//     ratingNum: 5,
//     reviews: 120,
//     tags: "Japanese",
//     add: "567 Clarke Rd #107, Coquitlam, BC V3J 0K7",
//     mapString: "mockMap.png",
//   },
//   {
//     id: 2,
//     name: "Haruua",
//     ratingNum: 5,
//     reviews: 120,
//     tags: "Spanish",
//     add: "Vancouver, BC V3J 0K7",
//     mapString: "mockMap.png",
//   },
//   {
//     id: 3,
//     name: "Saku",
//     ratingNum: 5,
//     reviews: 120,
//     tags: "Japanese",
//     add: "567 Clarke Rd #107, Coquitlam, BC V3J 0K7",
//     mapString: "mockMap.png",
//   },
//   {
//     id: 4,
//     name: "Saku",
//     ratingNum: 5,
//     reviews: 120,
//     tags: "Japanese",
//     add: "567 Clarke Rd #107, Coquitlam, BC V3J 0K7",
//     mapString: "mockMap.png",
//   },
//   {
//     id: 5,
//     name: "Saku",
//     ratingNum: 5,
//     reviews: 120,
//     tags: "Japanese",
//     add: "567 Clarke Rd #107, Coquitlam, BC V3J 0K7",
//     mapString: "mockMap.png",
//   },
//   {
//     id: 6,
//     name: "Saku",
//     ratingNum: 5,
//     reviews: 120,
//     tags: "Japanese",
//     add: "567 Clarke Rd #107, Coquitlam, BC V3J 0K7",
//     mapString: "mockMap.png",
//   },
//   {
//     id: 7,
//     name: "Saku",
//     ratingNum: 5,
//     reviews: 120,
//     tags: "Japanese",
//     add: "567 Clarke Rd #107, Coquitlam, BC V3J 0K7",
//     mapString: "mockMap.png",
//   },
// ];
